### ISSUE TITLE
Installation Lab

### ISSUE THREAD

**Issue by bigfnj** [bigfnj/SEBC#1]

**Comment by bigfnj** [comment]
![account pending validation](https://cloud.githubusercontent.com/assets/13438147/18647421/c930fa9e-7e6a-11e6-9220-1709c4aa6dcf.png)

Account Pending Validation (AWS)

**Comment by bigfnj** [comment]
![2016-09-19_20-57-15](https://cloud.githubusercontent.com/assets/13438147/18653967/b68113e8-7eab-11e6-8fd9-03dd92c704e9.png)

**Comment by bigfnj** [comment]
Going to follow MySQL

http://www.cloudera.com/documentation/enterprise/latest/topics/cm_ig_mysql.html

**Comment by bigfnj** [comment]
![2016-09-19_21-37-37](https://cloud.githubusercontent.com/assets/13438147/18654724/6341a408-7eb1-11e6-8e48-e142736d22fe.png)

**Comment by bigfnj** [comment]
********

**Comment by bigfnj** [comment]
HOLY CRAP THIS TOOK FOREVER!!!!!!!!!

![2016-09-20_2-34-32](https://cloud.githubusercontent.com/assets/13438147/18659809/f3521040-7eda-11e6-8bdd-76f91a3e5b7a.png)

**Comment by bigfnj** [comment]
**Synching instantly---- YAY! Going to bed its 3am!**

![2016-09-20_2-38-19](https://cloud.githubusercontent.com/assets/13438147/18659902/774a2a54-7edb-11e6-9f72-dd6f491ee8a8.png)

**Comment by bigfnj** [comment]
Cloudera Manager wont start.... le sigh ><
![2016-09-20_9-51-42](https://cloud.githubusercontent.com/assets/13438147/18672914/ed8cc7da-7f17-11e6-9fb4-9e77cd8cadb1.png)

**Comment by bigfnj** [comment]
HOLY CRAP... terrible documentation.... so long story in a nutshell: MUST USE SAME hostname as when installed MySQL (I used the internal DNS name). Set that in the config..... then following cloudera instruction it sort of "skips" the part where you must run the db create script..... did that.... then I needed to flush the tables in MySQL (not in the documentation but on cloudera support forums. once flushed I needed to add the LINE: binlog_format = mixed (again in the support forums, but not in the documentation). anyways its working!

![2016-09-20_11-38-45](https://cloud.githubusercontent.com/assets/13438147/18677455/d79038ea-7f26-11e6-8d72-1bd923708aa3.png)

**Comment by bigfnj** [comment]
Hosts failed to show up, had to resize the root partition in order to gain space... this corrected all of the issues with the installation wizard... moving along.... albeit annoyingly so lol.

**Comment by bigfnj** [comment]
Another thing that should be noted..... in my case HIVE would NOT use a blank password. It tests ok, but then flat refuses to login to the mysql server. I created another account WITH a password, then granted it *.* privileges.... then input that into the configuration. Then it deployed..... (lalala 3 hours later).
![2016-09-20_15-31-30](https://cloud.githubusercontent.com/assets/13438147/18685761/5ea9a6b6-7f47-11e6-8f98-0d07632dcf82.png)

**Comment by bigfnj** [comment]
iptables stopped mah zookeeperz from workin'...... disable dat pile of firewalling!

**Comment by mfernest** [comment]
Wow, you hit just about all the speed bumps! Big ups for persistence.

File content is all good.

Completed.
