### ISSUE TITLE
Storage Labs

### ISSUE THREAD

**Issue by bigfnj** [bigfnj/SEBC#2]
Create folder....
oops - no permissions. have to change user and make directory

![2016-09-20_16-57-32](https://cloud.githubusercontent.com/assets/13438147/18688709/838c9c2a-7f53-11e6-9901-833cf1e083c9.png)

**Comment by bigfnj** [comment]
Teragen works in bytes.... yuck

**Comment by bigfnj** [comment]
This makes for craziness...
sudo -u hdfs hadoop jar /opt/cloudera/parcels/CDH-5.8.0-1.cdh5.8.0.p0.42/lib/hadoop-0.20-mapreduce/hadoop-examples.jar teragen 5000000 /user/vtrhyno/terasort-input

![2016-09-20_17-16-56](https://cloud.githubusercontent.com/assets/13438147/18689219/0fbfc8a0-7f56-11e6-905e-d03ddc19519b.png)

**Comment by mikeridley** [comment]
Teragen...sort of works in bytes.  It works in chunks of 100 byte records.

**Comment by bigfnj** [comment]
Unable to "Replicate" data across datacenters due to the route losing the ability to route to the internal data nodes: ERROR: Caused by: java.net.UnknownHostException: ip-10-0-1-230.ec2.internal
![2016-09-20_17-46-35](https://cloud.githubusercontent.com/assets/13438147/18690070/53047c4c-7f5a-11e6-85c3-5a1df680973e.png)

**Comment by bigfnj** [comment]
decided to go crazy and write over 10 TB of data...oops... deleted and restarted this morning.

File Output Format Counters 
                Bytes Written=10737418200
7.19user 0.84system 2:25.51elapsed 5%CPU (0avgtext+0avgdata 197552maxresident)k
152inputs+1544outputs (1major+70081minor)pagefaults 0swaps

**Comment by bigfnj** [comment]
![2016-09-21_9-11-00](https://cloud.githubusercontent.com/assets/13438147/18712227/6f549b76-7fdb-11e6-9bbf-261f6764608d.png)

**Comment by bigfnj** [comment]
~ 
:) root@ip-172-31-44-50 # hdfs cacheadmin -listPools
Found 1 result.
NAME          OWNER  GROUP  MODE            LIMIT  MAXTTL
swimmingpool  hdfs   hdfs   rwxr-xr-x   unlimited   never

**Comment by bigfnj** [comment]
made a few mistakes w/ the pool & cache so had to start over. re-generated data, re set up the pool & directive, then did the first run

**FIRST RUN**

![2016-09-21_10-40-07](https://cloud.githubusercontent.com/assets/13438147/18715587/e25e1ff0-7fe7-11e6-9f5c-08941f349ec8.png)

**Comment by bigfnj** [comment]
12.35user 1.30system 6:22.80elapsed

**Comment by bigfnj** [comment]
yay, all fixed!

~ 
:( root@ip-172-31-44-50 # hdfs cacheadmin -listDirectives -stats                                    
Found 1 entry
 ID POOL           REPL EXPIRY  PATH                        BYTES_NEEDED  BYTES_CACHED  FILES_NEEDED  FILES_CACHED
  2 swimmingpool      1 never   /user/bigfnj/terasort-gen    10737418200   10737418200             3             3

~ 
:) root@ip-172-31-44-50 # hdfs cacheadmin -listPools -stats                                                            
Found 1 result.
NAME          OWNER  GROUP  MODE            LIMIT  MAXTTL  BYTES_NEEDED  BYTES_CACHED  BYTES_OVERLIMIT  FILES_NEEDED  FILES_CACHED
swimmingpool  hdfs   hdfs   rwxr-xr-x   unlimited   never   10737418200   10737418200                0             3             3


![2016-09-21_11-03-25](https://cloud.githubusercontent.com/assets/13438147/18716501/0ebf97ce-7feb-11e6-8395-c68106abe07d.png)

**Comment by bigfnj** [comment]
Ok, updated 1st run stats
**10.09user 1.22system 6:21.80elapsed**

**Comment by bigfnj** [comment]
2nd run... incredibly _underwhelmed._

**9.93user 1.19system 5:57.03elapsed**

**Comment by mfernest** [comment]
You really need greater more nodes and data for the cache feature to show a meaningful difference. Remember it's a hedge against disk-based batch processing tasks. Cutting a 4-hour job to 3.5, that's not nothing. With a little cache hit rate analysis you can get up to 15-18% performance reduction.

**Comment by mfernest** [comment]
File content is good. And thank you for being one of a few who remembered to (re)name their cluster. Did I not say it often enough?

Complete
