### ISSUE TITLE
Resources Lab

### ISSUE THREAD

**Issue by bigfnj** [bigfnj/SEBC#4]
Not asked, but want to post notes
 
1st, not certain where to post the asked for screenshot!
![2016-09-21_16-36-16](https://cloud.githubusercontent.com/assets/13438147/18728075/92cbcabe-8019-11e6-9669-2850696201e6.png)

**Comment by bigfnj** [comment]
Could not find "Static Pools" so enabled pools control by group, which disabled the "Dynamic Pools" label and changed it to "Resource Pools" with an option to view dynamic pool status (odd)

**Comment by bigfnj** [comment]
Label at top though still reads Dynamic.... /confused

**Comment by bigfnj** [comment]
classmate help.... used the search... typed "Static" and opened up the link... maybe this is the chart page you wanted?

![2016-09-21_16-44-28](https://cloud.githubusercontent.com/assets/13438147/18728297/b03de7fc-801a-11e6-8ea5-6fa69e27a0bb.png)

**Comment by mikeridley** [comment]
If you click on Clusters at the top of the main page in Cloudera Manager you should get a drop down that will have two columns, a list of services on the left and some other stuff on the right.  On the right side column, you should see Static Service Pools and Dynamic Resource Pools.

**Comment by mikeridley** [comment]
(if you do not have that, for some reason, I will be puzzled and you should let me know because that will be new)

**Comment by bigfnj** [comment]
Its not there, which is where cloudera site says it should be. had to search. see my dropdown below.

![2016-09-21_16-50-14](https://cloud.githubusercontent.com/assets/13438147/18728540/9640d278-801b-11e6-8716-b9fe64a295b6.png)

**Comment by mikeridley** [comment]
![screen shot 2016-09-21 at 4 58 33 pm](https://cloud.githubusercontent.com/assets/2366410/18728777/c0ec5fb4-801c-11e6-8419-a98fb9537cd3.png)

**Comment by bigfnj** [comment]
script failed overnight due to sudo losing TTY (lame)... re-running now

**Comment by bigfnj** [comment]
did not catch the script not actually making 10G data set to process. Which explains a lot of the results I had gotten....

Anyways, here is the corrected version now that the lab has ended.


#!/bin/sh
# Confirm the path values given below correspond to your installation

HADOOP_MR=/opt/cloudera/parcels/CDH/lib/hadoop-0.20-mapreduce
HADOOP_PATH=/opt/cloudera/parcels/CDH/bin

# Mark start of the loop
echo Testing loop started on `date`

# Mapper containers
for i in 2 4 8 16 32 64
do
   # Reducer containers
   for j in 2 4 8 16 32 64
   do                 
      # Container memory
      for k in 512 1024 2048 
      do                         
         # Set mapper JVM heap 
         MAP_MB=`echo "($k*0.8)/1" | bc` 

         # Set reducer JVM heap 
         RED_MB=`echo "($k*0.8)/1" | bc` 

echo ""
echo "Mappers $i, Reducers $j, Memory $k "
echo ""
echo "Begin GEN"
echo ""

   time sudo -u hdfs $HADOOP_PATH/hadoop jar $HADOOP_MR/hadoop-examples.jar teragen \
                     -Dmapreduce.job.maps=$i \
                     -Dmapreduce.map.memory.mb=$k \
                     -Dmapreduce.map.java.opts.max.heap=$MAP_MB \
                     107374182 /results/tg-10GB-${i}-${j}-${k} 1>tera_${i}_${j}_${k}.out 2>tera_${i}_${j}_${k}.err                       

echo ""
echo "Begin SORT"
echo ""

   time sudo -u hdfs $HADOOP_PATH/hadoop jar $HADOOP_MR/hadoop-examples.jar terasort \
                     -Dmapreduce.job.maps=$i \
                     -Dmapreduce.job.reduces=$j \
                     -Dmapreduce.map.memory.mb=$k \
                     -Dmapreduce.map.java.opts.max.heap=$MAP_MB \
                     -Dmapreduce.reduce.memory.mb=$k \
                     -Dmapreduce.reduce.java.opts.max.heap=$RED_MB \
                     /results/tg-10GB-${i}-${j}-${k}  \
                     /results/ts-10GB-${i}-${j}-${k} 1>>tera_${i}_${j}_${k}.out 2>>tera_${i}_${j}_${k}.err                         

echo ""
echo ""

        sudo -u hdfs $HADOOP_PATH/hadoop fs -rm -r -skipTrash /results/tg-10GB-${i}-${j}-${k}                         
        sudo -u hdfs $HADOOP_PATH/hadoop fs -rm -r -skipTrash /results/ts-10GB-${i}-${j}-${k}                 
      done
   done
done

echo Testing loop ended on `date`

**Comment by mfernest** [comment]
Yeesh, I didn't think this lab could be that confusing. I will take it through the typewriter at my next opportunity and make it clearer.

Calling this Complete.
