### ISSUE TITLE
Security Lab

### ISSUE THREAD

**Issue by bigfnj** [bigfnj/SEBC#5]
ran into a pile of garbage on this one.
-Enabling TLS for agent communication to SCM Server borks. the server refuses to start looking for a keystore.

Initially I thought I checked the wrong option, but upon looking into the database, found that I had indeed checked the correct option. To validate, we undid the change.... loaded cloudera manager, and checked the box again. restarted and the same issue occurred. EVIL!

Here is the fix screen. Inevitably giving up on enabling TLS communication to agents.
![2016-09-22_13-02-29](https://cloud.githubusercontent.com/assets/13438147/18759738/de5b7954-80cb-11e6-955c-0930a2972f1a.png)

**Comment by bigfnj** [comment]
went back and attempted to fix the keystore anyways... received some weird errors. I know how to correct them and generate valid keys, but following the documentation provided proves to be ..... lets say.... .challenging.

~ 
:) root@ip-172-31-44-47 # keytool -importcert -trustcacerts -alias RootCA -keystore /opt/cloudera/security/jks/cmhost-keystore.jks -file /opt/cloudera/security/CAcerts/RootCA.cer -storepass password
keytool error: java.lang.Exception: Input not an X.509 certificate

**Comment by bigfnj** [comment]
Threw out a lifeline, we decided to use self-signed certs and build the keystore. It was done with the following commands:

keytool -genkeypair -alias ip-172-31-44-47 -keyalg RSA -keystore \
/opt/cloudera/security/jks/cmhost-keystore.jks -keysize 2048 -dname \
"CN=ip-172-31-44-47.us-west-2.compute.internal,OU=Support,O=Cloudera,L=Denver,ST=Colorado,C=US" \
-storepass password -keypass password


keytool -certreq -alias ip-172-31-44-47 \
-keystore /opt/cloudera/security/jks/cmhost-keystore.jks \
-file /opt/cloudera/security/x509/cmhost.csr -storepass password \
-keypass password


keytool -genkeypair -keystore node1.keystore -keyalg RSA \
-alias node1 -dname "CN=node1.example.com,O=Hadoop" \
-storepass changeme -keypass changeme -validity 999


From there I enabled TLS communication with the agents and restarted. Everything came up!!!. 

~~ also had to input the path into cloudera manager directly pointing at the keystore

**Comment by bigfnj** [comment]
4 of the 5 nodes came online with TLS enabled... .the last one (the master node) node1.... the config had itself set as "localhost" so it failed with TLS.... modified the config file so it would point to itself using the FQDN resolved the issue. Yay!
![2016-09-22_15-13-40](https://cloud.githubusercontent.com/assets/13438147/18762579/51551b30-80d7-11e6-809b-71e951c5bd28.png)

**Comment by bigfnj** [comment]
Getting that Kerberos installed!
![2016-09-22_15-30-29](https://cloud.githubusercontent.com/assets/13438147/18763046/9cf3dcf0-80d9-11e6-9552-9860aee81510.png)

**Comment by bigfnj** [comment]
Kerberos documentation for the server is a little confusing.... thanks for the help... got a working config!!

:) root@ip-172-31-44-51 # vi /etc/krb5.conf 
[logging]
 default = FILE:/var/log/krb5libs.log
 kdc = FILE:/var/log/krb5kdc.log
 admin_server = FILE:/var/log/kadmind.log

[libdefaults]
 default_realm = BIGFNJ
 dns_lookup_realm = false
 dns_lookup_kdc = false
 ticket_lifetime = 24h
 renew_lifetime = 7d
 forwardable = true

[realms]
 BIGFNJ = {
  kdc = ec2-52-33-107-148.us-west-2.compute.amazonaws.com
  admin_server = ec2-52-33-107-148.us-west-2.compute.amazonaws.com
 }

[domain_realm]
 .amazonaws.com = BIGFNJ
 amazonaws.com = BIGFNJ

**Comment by bigfnj** [comment]
Location of the three config files
![2016-09-22_16-37-37](https://cloud.githubusercontent.com/assets/13438147/18765262/eacdbe06-80e2-11e6-81bd-683c52fc3b93.png)

**Comment by bigfnj** [comment]
kinit FINALLY working!!
![2016-09-22_16-39-10](https://cloud.githubusercontent.com/assets/13438147/18765316/235e4a88-80e3-11e6-8f6e-44e1bebdce54.png)

**Comment by bigfnj** [comment]
adding keytabs for each host
![2016-09-22_16-51-36](https://cloud.githubusercontent.com/assets/13438147/18765703/df639eee-80e4-11e6-8744-28ef8da1cffa.png)

**Comment by bigfnj** [comment]
had to add root to the ACL & initialize in order to get the hosts to connect

:) root@ip-172-31-44-51 # vi /var/kerberos/krb5kdc/kadm5.acl 
*/admin@BIGFNJ  *
cloudera-scm    admilc
root/admin@BIGFNJ       *

# /usr/sbin/kadmin.local -q "addprinc root/admin"

**Comment by bigfnj** [comment]
conf edits for non zero

#edits
max_life = 1d
max_renewable_life = 7d
kdc_tcp_ports = 88
krb5_lifetime = 24h
krb5_renewable_lifetime = 9d

**Comment by bigfnj** [comment]
ktadd -k /etc/krb5.keytab ip-172-31-44-50/ec2-54-70-153-42.us-west-2.compute.amazonaws.com
ktadd -k /etc/krb5.keytab ip-172-31-44-48/ec2-52-38-26-86.us-west-2.compute.amazonaws.com
ktadd -k /etc/krb5.keytab ip-172-31-44-49/ec2-54-70-168-83.us-west-2.compute.amazonaws.com
ktadd -k /etc/krb5.keytab ip-172-31-44-47/ec2-52-43-85-13.us-west-2.compute.amazonaws.com
ktadd -k /etc/krb5.keytab ip-172-31-44-51/ec2-52-33-107-148.us-west-2.compute.amazonaws.com

addprinc -randkey  ip-172-31-44-50/ec2-52-33-107-148.us-west-2.compute.amazonaws.com
addprinc -randkey  ip-172-31-44-48/ec2-52-33-107-148.us-west-2.compute.amazonaws.com
addprinc -randkey  ip-172-31-44-49/ec2-52-33-107-148.us-west-2.compute.amazonaws.com
addprinc -randkey  ip-172-31-44-47/ec2-52-33-107-148.us-west-2.compute.amazonaws.com
addprinc -randkey  ip-172-31-44-51/ec2-52-33-107-148.us-west-2.compute.amazonaws.com



kadmin:  addprinc -randkey ip-172-31-44-50/ec2-54-70-153-42.us-west-2.compute.amazonaws.com
WARNING: no policy specified for ip-172-31-44-50/ec2-54-70-153-42.us-west-2.compute.amazonaws.com@BIGFNJ; defaulting to no policy
Principal "ip-172-31-44-50/ec2-54-70-153-42.us-west-2.compute.amazonaws.com@BIGFNJ" created.

kadmin:  addprinc -randkey ip-172-31-44-48/ec2-52-38-26-86.us-west-2.compute.amazonaws.com
WARNING: no policy specified for ip-172-31-44-48/ec2-52-38-26-86.us-west-2.compute.amazonaws.com@BIGFNJ; defaulting to no policy
Principal "ip-172-31-44-48/ec2-52-38-26-86.us-west-2.compute.amazonaws.com@BIGFNJ" created.

kadmin:  addprinc -randkey ip-172-31-44-49/ec2-54-70-168-83.us-west-2.compute.amazonaws.com
WARNING: no policy specified for ip-172-31-44-49/ec2-54-70-168-83.us-west-2.compute.amazonaws.com@BIGFNJ; defaulting to no policy
Principal "ip-172-31-44-49/ec2-54-70-168-83.us-west-2.compute.amazonaws.com@BIGFNJ" created.

kadmin:  addprinc -randkey ip-172-31-44-47/ec2-52-43-85-13.us-west-2.compute.amazonaws.com
WARNING: no policy specified for ip-172-31-44-47/ec2-52-43-85-13.us-west-2.compute.amazonaws.com@BIGFNJ; defaulting to no policy
Principal "ip-172-31-44-47/ec2-52-43-85-13.us-west-2.compute.amazonaws.com@BIGFNJ" created.

kadmin:  addprinc -randkey ip-172-31-44-51/ec2-52-33-107-148.us-west-2.compute.amazonaws.com
WARNING: no policy specified for ip-172-31-44-51/ec2-52-33-107-148.us-west-2.compute.amazonaws.com@BIGFNJ; defaulting to no policy
Principal "ip-172-31-44-51/ec2-52-33-107-148.us-west-2.compute.amazonaws.com@BIGFNJ" created.

**Comment by bigfnj** [comment]
apparantly, however amazon formats their hostnames I am doing it wrong ><
![2016-09-22_17-40-47](https://cloud.githubusercontent.com/assets/13438147/18767210/cbbaecb0-80eb-11e6-9c31-78442195ed95.png)

**Comment by bigfnj** [comment]
I need to figure out how to format amazons silly hostnames to domain pairing and add it as a principle for this to work properly.... /confused

**Comment by bigfnj** [comment]
ok... using kinit realized that cloudera-scm would ONLY work when adding /admin after it.. .even though its not that way in the ACL.
![2016-09-22_17-53-41](https://cloud.githubusercontent.com/assets/13438147/18767506/8ab5fa1e-80ed-11e6-8254-c894a8d8b0c9.png)

**Comment by bigfnj** [comment]
HOLY MOLY!!!! IT WORKED!!!!!
AAAAAAAAAAAAAAHHHHHHHHHHHHHHHHHHHHHHHHHHHH
![2016-09-22_17-58-17](https://cloud.githubusercontent.com/assets/13438147/18767598/33eb9918-80ee-11e6-91c6-44483d07bfac.png)

**Comment by bigfnj** [comment]
Installing sentry....
![2016-09-22_18-45-30](https://cloud.githubusercontent.com/assets/13438147/18768664/dec7fe3e-80f4-11e6-88eb-f94e8480741f.png)

**Comment by bigfnj** [comment]
*Side-Note.... i double checked 3x that I had renewable tickets.... they are not working. double checked config. it apparently ignored my entry because it exceeded 7 days. cluster hosed. hahaha. oh well its late, going to prep for tomorrow.

**Comment by mfernest** [comment]
Wow. That, my friend, is a whole journey.

I don't recall if we spoke about this in class, but what prompted you to go after TLS configuration first?

I don't believe this entry in your `kadm5.acl` will work: `cloudera-scm	admilc` because no realm is specified. 

The two way to fix your renewable ticket issue are to hack the attribute directly in the Kerberos database or set the renewable flag explicitly in your `kdc.conf`, re-create the database, and restart your services.

Quite the adventure, again! I'm really feeling bad now my time got sucked up at the office on Friday. All rounds are on me when we meet again!

Complete
