### ISSUE TITLE
 Install MySQL

### ISSUE THREAD

**Issue by bigfnj** [bigfnj/SEBC#7]

**Comment by bigfnj** [comment]
•Install MySQL 5.5.x server using the YUM repository from  dev.mysql.com 
http://dev.mysql.com/get/mysql57-community-release-el6-9.noarch.rpm

**Comment by bigfnj** [comment]
oops installed wrong version... fixed it!

**Comment by bigfnj** [comment]
innodb failed to initialize... GRRRRRRRRRRRRRRRRRRRRRRRR

Solution:

The next step was to check the mysql logs and I saw the error:

InnoDB: Error: log file ./ib_logfile0 is of different size 0 5256780 bytes
InnoDB: than specified in the .cnf file 0 1077645824 bytes!
[ERROR] Plugin ‘InnoDB’ init function returned error.
[ERROR] Plugin ‘InnoDB’ registration as a STORAGE ENGINE failed.
[ERROR] Unknown/unsupported storage engine: InnoDB
[ERROR] Aborting

The solution for this error is:

Remove the ib_logfile0 and ib_logfile1 files located in /var/lib/mysql.

rm /var/lib/mysql/ib_logfile0
rm /var/lib/mysql/ib_logfile1

**Comment by bigfnj** [comment]
![2016-09-23_9-53-24](https://cloud.githubusercontent.com/assets/13438147/18788105/a03528e8-8173-11e6-82a8-81e35de70b01.png)

**Comment by bigfnj** [comment]
![2016-09-23_9-59-42](https://cloud.githubusercontent.com/assets/13438147/18788352/7e190f26-8174-11e6-911b-a3d607d60e3b.png)

**Comment by mfernest** [comment]
Been down this specific path more often than I care to remember.

Completed
