### ISSUE TITLE
 Install CM

### ISSUE THREAD

**Issue by bigfnj** [bigfnj/SEBC#8]
Here we go!

**Comment by bigfnj** [comment]
repo had bad permissions for some reason... redownloaded

wget https://archive.cloudera.com/cm5/redhat/5/x86_64/cm/cloudera-manager.repo

then modified install path to pull version 5.8.0

**Comment by bigfnj** [comment]
![2016-09-23_10-29-27](https://cloud.githubusercontent.com/assets/13438147/18789335/a7e4a9a6-8178-11e6-97ad-6ff3f89bec0b.png)

**Comment by bigfnj** [comment]
repos for labs
![2016-09-23_10-33-25](https://cloud.githubusercontent.com/assets/13438147/18789497/3c0b4b76-8179-11e6-841b-40182c0da642.png)

**Comment by bigfnj** [comment]
unable to connect to SQL..... will fix this
![2016-09-23_10-45-35](https://cloud.githubusercontent.com/assets/13438147/18789963/f282e084-817a-11e6-9105-6d56dea1a50a.png)

**Comment by bigfnj** [comment]
grant all on *.* to 'scm'@'52.40.42.167' identified by 'scm';
./scm_prepare_database.sh mysql -h 52.88.228.192 scm scm scm

/etc/cloudera-scm-server 
:) root@ip-172-31-3-85 # cat db.properties
# Auto-generated by scm_prepare_database.sh on Fri Sep 23 15:13:23 UTC 2016
#
# For information describing how to configure the Cloudera Manager Server
# to connect to databases, see the "Cloudera Manager Installation Guide."
#
com.cloudera.cmf.db.type=mysql
com.cloudera.cmf.db.host=52.88.228.192
com.cloudera.cmf.db.name=scm
com.cloudera.cmf.db.user=scm
com.cloudera.cmf.db.password=scm

**Comment by bigfnj** [comment]
![2016-09-23_11-22-38](https://cloud.githubusercontent.com/assets/13438147/18791278/163d820e-8180-11e6-93f9-19ac8373b62e.png)

**Comment by mfernest** [comment]
Completed.
