### ISSUE TITLE
 Install CDH

### ISSUE THREAD

**Issue by bigfnj** [bigfnj/SEBC#9]
![2016-09-23_11-34-29](https://cloud.githubusercontent.com/assets/13438147/18791689/c09a11bc-8181-11e6-8290-49e1966044c1.png)

**Comment by bigfnj** [comment]
The only way I found to modify to a specific version NOT supported by parcels was to switch to a package install.

**Comment by bigfnj** [comment]
Feeling that pressure!

![2016-09-23_11-50-57](https://cloud.githubusercontent.com/assets/13438147/18792340/14672576-8184-11e6-8a70-f8b5ebc376de.png)

**Comment by bigfnj** [comment]
![2016-09-23_11-59-43](https://cloud.githubusercontent.com/assets/13438147/18792638/433c9aa6-8185-11e6-8e4c-836180f3cf53.png)

**Comment by bigfnj** [comment]
~ 
:) root@ip-172-31-3-83 # hdfs dfs -ls /user
Found 6 items
drwxr-xr-x   - hdfs   supergroup          0 2016-09-23 16:01 /user/christie
drwxrwxrwx   - mapred hadoop              0 2016-09-23 15:53 /user/history
drwxrwxr-t   - hive   hive                0 2016-09-23 15:54 /user/hive
drwxrwxr-x   - hue    hue                 0 2016-09-23 15:55 /user/hue
drwxrwxr-x   - oozie  oozie               0 2016-09-23 15:55 /user/oozie
drwxr-xr-x   - hdfs   supergroup          0 2016-09-23 16:02 /user/weiner

**Comment by bigfnj** [comment]
![3_hue_installed png](https://cloud.githubusercontent.com/assets/13438147/18792922/801a643e-8186-11e6-8f96-aabe6e0b8bca.png)

**Comment by mfernest** [comment]
Completed
